(function (global) {
  function beat(t, who, text, kind, lane) {
    return { t: t, who: who, text: text, kind: kind || "work", lane: lane || "" };
  }

  const CLOCK = [
    beat("08:00", "Anyone free · Tracy", "Venue open. Tracy arrives sometime 8:00–10:00 with a complete lights and sound system. Ready to go. Setup Lead and the 3 dressers come at 10:00.", "arrive"),
    beat("08:10", "Anyone free · Tracy", "Wait for Tracy. Official production load in is 9:00. If you are free, ask him if he needs a hand. Ask someone else to come too.", "work"),
    beat("09:00", "Tracy · production", "Production load in. Complete lights and sound system. Furniture already placed.", "arrive"),
    beat("09:15", "Anyone free · Tracy", "Power mapped. Dance floor cables taped. Spare batteries at the mixer.", "work"),
    beat("09:30", "Anyone free · Tracy", "Bar stool staged for David. One vocal mic and stand ready.", "work"),
    beat("10:00", "Tracy · production", "System check. Lights and sound ready.", "work"),
    beat("10:00", "Setup Lead · Setup 1–3", "Paul Egan and the 3 dressers arrive. Concert t-shirts on. Furniture is already placed. Tracy is on system check.", "arrive"),
    beat("10:00", "Event Captain", "Available for setup help if they need a hand.", "work"),
    beat("10:05", "Setup Lead", "Yard signs along the path from the gate to the venue door. Paul puts them out.", "work"),
    beat("10:05", "Setup 1–3", "Walk the room, exits, and lobby. Then dress the 8 guest tables only.", "work"),
    beat("10:25", "Setup 3 / Campaign", "Tables done. Start the 30-minute merch set. Hang two banners with bungee cords. Table conversation cards on the guest tables. Cards, buttons, candy, shirts.", "work"),
    beat("10:25", "Setup 1 + 2", "Place printed signs. Dress the lobby ticket table.", "work"),
    beat("10:40", "Setup 1–3", "Set the tea and lemonade station. No ice yet. Ice waits until 4:30.", "work"),
    beat("11:00", "Setup 3", "Merch set done. Yard-sign sheet on the same table. First name + phone.", "work"),
    beat("12:00", "Tracy", "Lunch off site, 45 minutes, only if Tracy can hold the system.", "eat"),
    beat("12:30", "Setup 1–3", "Morning work is done. Leave. Eat a real lunch off site. Back at 4:30 in your night seat.", "leave"),
    beat("14:00", "David + band", "DAB load in. Band merch table and merch area go up now.", "arrive"),
    beat("15:00", "David + band", "DAB check. Night volunteers are not required yet.", "work"),
    beat("16:30", "David + band + Tracy", "Acoustic PA check. DAB loaded in at 2:00. Not 5:00.", "show"),
    beat("16:30", "Night crew", "Volunteers arrive at 4:30. Concert t-shirts on. Ice can go in now. Open Tonight. Stay off the dance floor.", "arrive"),
    beat("16:30", "Parking · crowd", "Arrive by 4:30. Eat at 4:40. On lot, path, and lobby at 5:15.", "arrive"),
    beat("16:30", "Tracy muscle", "Come at 4:30 if you can. Eat. No post until 8:45. Required at 8:45.", "arrive"),
    beat("16:32", "Ben + 3 servers", "Set the line now. Stay off the dance floor. Ben does not plate.", "work"),
    beat("16:35", "Drink station", "Ice in. Tea and lemonade full. Water on ice. Ask for donations. Stay off the dance floor.", "work"),
    beat("17:30", "Production Manager 1 + 2", "Arrive by 5:30 if you can. Keep the night on plan. Fill gaps. Point people. Ask if anyone needs a break. Eat if you have not.", "arrive"),
    beat("17:15", "Event Captain", "FOOD DOORS. You are there when they open. Dinner guests come in. Everything is inside. Concert-only stay in cars until GA doors 6:30. Available for questions and to fill in.", "work"),
    beat("17:15", "Parking", "On the lot. Food doors. Concert-only: stay in the car until 6:30. Overflow if it fills.", "work"),
    beat("17:15", "Parking · crowd", "Lot and lobby. Everything is inside. Food doors now. Concert-only stay in the car until 6:30.", "work"),
    beat("17:15", "Crowd", "Food doors. Lobby line off the doors. Point to tickets. Do not take money.", "work"),
    beat("17:15", "Tickets", "Food doors. Lobby table live: cash box, envelopes, $25 sign, kids $5 sign, educator/first-responder note.", "work"),
    beat("17:10", "Captain · tickets · campaign", "Eat now. 15 minutes. Do not start a meeting with food in your hand.", "eat"),
    beat("17:15", "Tracy", "Eat on your own seat. Tracy runs the acoustic set. Pitch in only if he asks.", "eat"),
    beat("17:25", "Tickets · campaign", "Back on posts. Table and lobby are live.", "work"),
    beat("17:15", "Ben + 3 servers", "BUFFET OPENS. Band dinner is now too. Ben directs. Servers serve. Drink donations — water, tea, or lemonade.", "show"),
    beat("17:30", "David + band", "Band dinner.", "eat"),
    beat("17:30", "Drink station", "Keep tea and lemonade full. Hand out water. Ask for donations. No set price.", "work"),
    beat("17:40", "Kelly Support · Photo", "Kelly is with guests. Support stays on her, vertical. Photo Lead roams.", "work"),
    beat("17:45", "Tracy · David", "Acoustic set starts. Center of the dance floor. 30 minutes. Stool, one mic, his amp only.", "show"),
    beat("17:45", "Ben + 3 servers · drink station · lot · lobby", "Stay on your job through this set. Listen from your post.", "work"),
    beat("17:45", "Production Manager 1", "Cover tickets if the table needs a break. Your call.", "work"),
    beat("17:45", "Production Manager 2", "Cover the food line for restroom only. Do not leave the buffet empty.", "work"),
    beat("17:45", "Tickets · campaign", "Stay on post unless a Production Manager relieves you.", "work"),
    beat("18:05", "Event Captain", "Stay findable. Questions, directions, fill a gap. Do not cut across the dance floor.", "work"),
    beat("18:10", "Tickets", "On the lobby table. Money stays with you.", "work"),
    beat("18:15", "David + band", "Acoustic over. Green room for 45 minutes. Concert is 7:00. Back at the stage by 6:50.", "sit"),
    beat("18:15", "Anyone free · Production Manager 2", "Acoustic over. Clear the floor. Stool away. Concert system up. Band is in the green room until 6:50.", "work"),
    beat("18:20", "Ben + servers", "Line slows. Second plate if you are still hungry. Then reset.", "eat"),
    beat("18:00", "Merch 2", "Arrive. Find the campaign table. You help the rush: donations, handouts, greet.", "arrive"),
    beat("18:25", "Campaign · Merch 2", "Table back up. Busiest window. Acoustic over to showtime. Donations, materials, greet.", "work"),
    beat("18:30", "Campaign · Merch 2", "Concert doors. Stay on the table. Greet. Hand materials. Take donations.", "work"),
    beat("18:30", "Event Captain", "CONCERT DOORS. You are there when they open. Available for questions, directions, and to fill in.", "work"),
    beat("18:30", "Tickets", "GA doors. Concert-only may leave the cars. 15-minute rush. No pile-up. Money stays with you.", "show"),
    beat("18:30", "David + band", "Preshow. Stay in the green room or at the stage. Not a second PA check.", "show"),
    beat("18:30", "Parking · crowd", "Concert-only out of cars now. Last line push. Then stand down unless Event Captain keeps you.", "work"),
    beat("18:40", "Parking · crowd", "Stand down. You may watch the whole concert.", "sit"),
    beat("18:45", "Event Captain · Tracy", "Hard checkpoint. Every post still has a body. Concert at 7:00.", "work"),
    beat("18:50", "Tickets", "Rush is over. Money stays with you.", "work"),
    beat("19:00", "Whole room", "Concert starts. Production Managers walk. One person always circulating. Phone on silent.", "show"),
    beat("19:15", "Campaign", "Stay on the table unless a Production Manager relieves you.", "work"),
    beat("19:15", "Merch 2", "Rush is over. Watch the concert if the table is quiet.", "work"),
    beat("19:20", "Ben + 3 servers", "Line is closed. Watch the concert if you are free. Merch keeps taking drink donations.", "work"),
    beat("19:20", "Drink station", "Stay on drinks unless a Production Manager relieves you.", "work"),
    beat("19:30", "Production Manager 1", "Keep walking if the other manager is sitting. Your call.", "work"),
    beat("20:00", "Drink station", "Back on the drink station through the last song. Ice, tea, lemonade, water, donations.", "work"),
    beat("20:00", "Production Manager 2", "Watch the concert if the floor is covered. Your call.", "work"),
    beat("20:15", "Production Manager 1", "Up. One quiet loop.", "work"),
    beat("20:30", "Event Captain", "HOUSE CLOSING. You are there when doors close. Last check starts after the show.", "work"),
    beat("20:45", "Tickets", "Reconcile tickets, merch, and drink donations. Money stays with you.", "strike"),
    beat("20:40", "Tracy muscle 1–3", "At the stage. Concert t-shirts on. Find Tracy.", "arrive"),
    beat("20:45", "Event Captain", "Show over. Call pairs out loud. Send 3 muscle to Tracy. Venue tables and chairs stay.", "strike"),
    beat("20:46", "Strike A", "Two people. 8 guest cloths plus buffet and lobby cloths. Leave venue furniture.", "strike"),
    beat("20:46", "Strike B", "Campaign and merch. Two banners + bungees down. Return table conversation cards. Bins, leftover shirts. 20 minutes.", "strike"),
    beat("20:46", "Strike C", "Ben plus 3 servers. Coolers, leftover, trash. 20 minutes.", "strike"),
    beat("20:46", "Strike D", "Tracy directs. Anyone free plus 3 muscle. No empty hands. His vehicle.", "strike"),
    beat("20:46", "Drink station", "Tickets collects drink donations. Pack leftover water. Empty tea and lemonade.", "strike"),
    beat("21:15", "David + band", "Load out. Band cases, merch table, merch area.", "strike"),
    beat("21:15", "Event Captain", "Cloths packed. Campaign packed. Food packed. Production should be loading.", "strike"),
    beat("21:30", "Tracy + muscle", "Carry should be done. Stage empty.", "strike"),
    beat("21:45", "Event Captain", "LAST CHECK. You are the last one. Restrooms, lot, lobby, main room. Our stuff is gone. Furniture stays.", "strike"),
    beat("22:00", "Event Captain", "Building checked. Thank Tracy and Ben. You leave last.", "done"),
  ];

  function hm(t) {
    const p = String(t || "").split(":");
    const h = Number(p[0]);
    const m = p[1] || "00";
    if (!Number.isFinite(h)) return t;
    const ampm = h >= 12 ? "PM" : "AM";
    return (h % 12 || 12) + ":" + m + " " + ampm;
  }

  function idFor(row, i) {
    return row.t + ":" + i + ":" + String(row.who || "").slice(0, 24);
  }

  const BAND = [
    beat("06:00", "David + band", "Bus call.", "arrive"),
    beat("08:00", "David + band", "Royse City bus call.", "arrive"),
    beat("09:00", "Tracy · production", "Production load in. Complete lights and sound system. Furniture already placed. Do not rebuild the room.", "arrive"),
    beat("10:00", "Tracy · production", "System check. Band is not required this morning.", "work"),
    beat("12:00", "Tracy", "Lunch off site, 45 minutes, only if the system can hold.", "eat"),
    beat("14:00", "David + band", "DAB load in. Band merch table and merch area go up now.", "arrive"),
    beat("15:00", "David + band", "DAB check.", "work"),
    beat("16:30", "David + band + Tracy", "Acoustic PA check. Stay off the dance floor when you are not on it.", "show"),
    beat("17:15", "House", "Food doors. Dinner guests come in. Concert-only stay in cars until 6:30.", "work"),
    beat("17:30", "David + band", "Band dinner.", "eat"),
    beat("17:45", "David + Tracy", "Acoustic set. 5:45–6:15. Center of the dance floor. Stool, one mic, his amp only.", "show"),
    beat("18:15", "David + band", "Acoustic over. Green room. Preshow is 6:30. Set is 7:00.", "sit"),
    beat("18:15", "Tracy · anyone free", "Clear the floor. Concert system up. Band is off the floor until preshow.", "work"),
    beat("18:30", "David + band", "GA doors. Preshow. Concert-only come in from the cars.", "show"),
    beat("19:00", "David + band", "Set. Full system. Last song about 8:45.", "show"),
    beat("20:45", "David + band + Tracy", "Strike stage. House production strike. Venue tables and chairs stay.", "strike"),
    beat("21:15", "David + band", "Load out. Band cases, merch table, merch area.", "strike"),
    beat("22:00", "House", "Building curfew.", "done"),
  ];

  const HOUSE = [
    beat("08:00", "Anyone free · Tracy", "Venue open. Tracy arrives 8:00–10:00 with a complete lights and sound system. Setup Lead and the 3 dressers come at 10:00.", "arrive", "setup"),
    beat("08:10", "Anyone free · Tracy", "Wait for Tracy. Official production load in is 9:00.", "work", "setup"),
    beat("09:00", "Tracy · production", "Production load in. Complete lights and sound system.", "arrive", "setup"),
    beat("09:15", "Anyone free · Tracy", "Power mapped. Dance-floor cables taped.", "work", "setup"),
    beat("09:30", "Anyone free · Tracy", "Bar stool and one vocal mic staged for David.", "work", "setup"),
    beat("10:00", "Tracy · production", "System check.", "work", "setup"),
    beat("10:00", "Setup Lead · Setup 1–3", "Paul Egan and the 3 dressers arrive. Dress the room. Furniture already placed. Tracy is on system check.", "arrive", "setup"),
    beat("10:00", "Event Captain", "Available for setup help if they need a hand.", "work", "setup"),
    beat("10:05", "Setup Lead", "Yard signs along the path from the gate to the door. Paul puts them out.", "work", "setup"),
    beat("10:05", "Setup 1–3", "Walk room, exits, lobby. Dress 8 guest tables only.", "work", "setup"),
    beat("10:25", "Setup 3 / Campaign", "30-minute merch set. Hang two banners with bungee cords. Table conversation cards on the guest tables.", "work", "setup"),
    beat("10:25", "Setup 1 + 2", "Printed signs up. Dress the lobby ticket table.", "work", "setup"),
    beat("10:40", "Setup 1–3", "Tea and lemonade station. No ice until 4:30.", "work", "setup"),
    beat("11:00", "Setup 3", "Merch done. Yard-sign sheet on the table.", "work", "setup"),
    beat("12:00", "Tracy", "Lunch 45 minutes only if the system can hold.", "eat", "setup"),
    beat("12:30", "Setup 1–3", "Morning setup done. Leave. Back at 4:30 in night seats.", "leave", "setup"),
    beat("14:00", "David + band", "DAB load in. Band merch table and merch area go up now.", "arrive", "arrive"),
    beat("15:00", "David + band", "DAB check. Night volunteers are not required yet.", "work", "arrive"),
    beat("16:30", "David + band + Tracy", "Acoustic PA check.", "arrive", "arrive"),
    beat("16:30", "Night crew", "Volunteers arrive at 4:30. T-shirts on. Ice can go in now. Stay off the dance floor.", "arrive", "arrive"),
    beat("16:30", "Parking · crowd", "Arrive by 4:30. Eat at 4:40. On lot, path, and lobby at 5:15.", "arrive", "arrive"),
    beat("17:15", "Event Captain", "FOOD DOORS. You are there when they open.", "work", "start"),
    beat("17:15", "Parking · crowd · tickets", "FOOD DOORS. Come in for dinner. Concert-only stay in cars until GA doors 6:30.", "arrive", "start"),
    beat("17:15", "Ben + 3 servers", "BUFFET OPENS. Band dinner is now too.", "show", "start"),
    beat("17:45", "David + Tracy", "DAVID STARTS. Acoustic 5:45–6:15. Inside, center of the dance floor.", "show", "start"),
    beat("18:15", "David + band", "ACOUSTIC ENDS. Green room 45 minutes. Back at the stage by 6:50.", "sit", "end"),
    beat("18:15", "Tracy + Production Manager 2", "Floor clear. Concert system up.", "work", "end"),
    beat("18:15", "Campaign · Merch 2", "Table back up. Rush window. Handouts and greet until showtime. Tickets collects the money.", "work", "start"),
    beat("18:30", "Event Captain", "CONCERT DOORS. You are there when they open.", "work", "start"),
    beat("18:30", "Tickets", "GA DOORS. Concert-only leave the cars. 15-minute rush. Preshow. Money stays with you.", "show", "start"),
    beat("18:45", "Captain · Tracy", "Hard checkpoint. Every post has a body. Concert at 7:00.", "work", "start"),
    beat("18:50", "David + band", "Band leaves green room. On stage for 7:00.", "arrive", "arrive"),
    beat("19:00", "Whole room", "CONCERT STARTS. Last song about 8:45.", "show", "start"),
    beat("20:40", "Tracy muscle 1–3", "Strike muscle arrives at the stage. Find Tracy.", "arrive", "arrive"),
    beat("20:45", "Whole room", "CONCERT ENDS. Strike starts. Venue furniture stays.", "strike", "end"),
    beat("20:46", "Strike A–D", "Cloths, merch, food, production. Anyone free + 3 muscle to Tracy.", "strike", "end"),
    beat("21:15", "David + band", "Load out. Band cases, merch table, merch area.", "strike", "end"),
    beat("21:15", "Event Captain", "Packs in vehicles. Production should be loading.", "strike", "end"),
    beat("21:30", "Tracy + muscle", "Stage empty. Cases in his vehicle.", "strike", "end"),
    beat("21:45", "Event Captain", "LAST CHECK. You are the last one. Restrooms, lot, lobby, main room.", "strike", "end"),
    beat("22:00", "Event Captain", "Last check done. You leave last.", "done", "end"),
  ];

  global.GGSRunOfShow = { CLOCK: CLOCK, BAND: BAND, HOUSE: HOUSE, hm: hm, idFor: idFor };
})(window);
