const S=[
['overview','Overview','Command board for Thursday. Every task has an owner and timing field.',[
['Event facts',['8:00 AM venue access','8 round 8-foot tables + 64 chairs','Horseshoe layout with open dance floor','4 rectangular buffet tables at entry','4-foot lobby ticket table','BBQ for 100; buffet service','5:30 PM BBQ/social hour','~5:45 PM David acoustic set for ~30 minutes','6:30 PM concert doors','7:00 PM concert','Show ends ~8:45–9:00 PM','Building cleared by 10:00 PM']],
['Tonight priorities',['Choose Event Captain','Assign 3-person setup crew','Assign event crew','Recruit 10–12+ dedicated teardown volunteers before Thursday','Announce teardown need early and offer free food to committed teardown volunteers','Confirm Ben food/service list','Confirm Tracy equipment list','Assign one campaign volunteer to assist Tracy','Inventory coolers/water','Finalize ticket/payment process','Assign vertical-only photo/video','Create load-out map']]]],
['ben','Ben / BBQ','Confirm exactly what Ben provides tonight. Use the owner field for the person handling each confirmation.',[
['Food for 100',['Pulled pork','Bread/buns','Potato salad','Baked beans','BBQ sauce/condiments','Serving pans/trays','Serving utensils','Tongs/ladles/spoons','Food covers','Warming/chafing equipment','Fuel if needed']],
['Disposable service',['Dinner plates — target 125','Forks — target 125','Knives — target 125','Spoons if needed — target 125','Napkins — target 125','Sandwich wrappers/baskets if needed','Cups if Ben provides them','Anything else Ben is providing']],
['Logistics',['Delivery/pickup','Exact food arrival time','Person receiving food','Ben setup requirements','Safe holding/serving plan','Equipment Ben needs from us','Final BEN PROVIDES list','Final WE PROVIDE list']]]],
['setup','Setup','Three people handle the complete general setup list. Tracy handles production/electrical with one campaign volunteer.',[
['3-person setup crew',['Assign Setup Person 1','Assign Setup Person 2','Assign Setup Person 3','All three handle tables/chairs','All three handle tablecloths','All three handle decorations','All three handle campaign materials','All three handle signs','All three handle lobby ticket setup','Confirm 8:00 AM arrival','Walk venue before unloading','Check exits/restrooms/guest flow','Position 8 round tables','Position 64 chairs','Build horseshoe','Create dance floor','Position 4 buffet tables','Position 4-foot lobby table','Set beverage station','Set sign pickup area','Set campaign display','Final room appearance check']],
['Tracy + campaign helper',['Confirm Tracy arrival','Assign campaign volunteer helper','Sound system','Speakers','Mixer','Microphones/mic stands','Instrument inputs','Speaker stands','Cables','Power strips','Extension cords','Gaffer/cable tape','Stage lights','Lighting stands','Spare batteries','Check outlets/circuits','Safe power distribution','Test microphones','Test inputs','Test speakers','Test lights','Full sound check','Add any Tracy-specific requirements']]]],
['volunteers','Volunteers','Build the roster before Thursday. Every person gets a job and arrival time.',[
['Morning setup — 8:00 AM',['Recruit exactly 3 setup people','Setup Person 1','Setup Person 2','Setup Person 3']],
['Event operations — 5:00 PM',['Event Captain','Primary ticket/check-in person','Ticket backup','BBQ/food service person 1','BBQ/food service person 2','Water/ice/cooler captain','Guest greeters','Campaign materials + sign distribution person','Photography/video person — vertical only','Kelly/guest-relations support','David/performer support','Venue/facilities person','Event runner/floater']],
['Teardown recruitment',['Recruit 10–12+ people before event','Record each teardown volunteer','Announce need early in event','Offer free food to committed teardown volunteers','Assign Strike Team A–E','Confirm team assignments before show ends','Teardown Captain']]]],
['tickets','Tickets & Money','Lock the admission and contribution process before doors.',[
['Lobby ticket station',['4-foot table','Tablecloth','Tickets','Guest list if applicable','Pens','Cash box/change','Electronic payment method if applicable','Ticket signage','Event information','Campaign QR codes','Backup paper process','Primary ticket person','Backup ticket person']],
['Ticket accounting',['Confirm ticket price(s)','Confirm cash acceptance','Confirm electronic payment method','Confirm refund/adjustment authority','Record ticket inventory before doors','Record tickets sold','Reconcile cash','Reconcile electronic payments','Secure event funds','Assign final reconciliation owner']],
['Contribution envelopes',['Prepare contribution envelopes','Prepare pens','Name field','Occupation field','Required contribution information fields','ANONYMOUS option for $25 contributions','$50 contribution envelope process','$100 contribution envelope process','Secure completed envelopes','Assign envelope custodian','End-of-night envelope count/reconciliation']]]],
['campaign','Campaign & Merch','Campaign materials, signs, Regnet Populis giveaways and concert shirts each need an owner.',[
['Campaign materials',['Kelly Grappe literature','Business/contact cards','Postcards','Door hangers if applicable','Buttons/stickers/pins','Campaign QR codes','Volunteer signup information','Donation information','Campaign display','Campaign materials owner']],
['100 yard signs',['Confirm 100 signs','Confirm 100 stakes','Count signs','Count stakes','Separate damaged signs','Bundle signs','Sign pickup station','Sign request/sign-out process','Campaign materials person handles distribution','Record recipient name','Record recipient contact','Record address/location as appropriate','Track distributed','Count remaining']],
['Road / entrance signs',['Kelly Grappe signs for roadside','Place roadside signs where permitted','Place entrance signs where permitted','Check before doors','Remove after event','Assign placement/removal owner']],
['Merchandise',['Pick up Grassroots & Guitar Strings concert T-shirts from T-shirt shop in North Little Rock','Confirm pickup time','Count shirts','Record sizes/quantities','Bring Regnet Populis shirts for giveaway','Set up merch table','Merch tablecloth','Concert T-shirt price/signage','Size display','Assign merch table owner','Payment method','Track shirts sold','Track Regnet Populis shirts given away','Secure remaining merchandise']]]],
['food','Food & Drinks','BBQ/social hour is 5:30–6:30 PM. We serve buffet style.',[
['Beverages',['Splenda sweet tea','Lemonade','Lots of bottled water','Glass serving container — sweet tea','Glass serving container — lemonade','Beverage dispensers/spigots','Cups if not supplied by Ben','Ice for tea/lemonade','Extra ice for coolers','As many ice chests/coolers as possible','Label personal coolers','Cooler captain','Fill coolers before guests','Set beverage station','Replenish water','Monitor/replenish ice','Collect/return coolers']],
['Buffet service',['Dress 4 buffet tables','Plan food flow','Plates','Utensils/napkins','Pulled pork','Bread/buns','Potato salad','Baked beans','Sauces/condiments','Serving utensils','Food covers','Safe hot/cold holding','Trash cans','Hand sanitizer/paper towels','BBQ service person 1','BBQ service person 2','Serve guests buffet style','Monitor/replenish buffet']],
['5:30–6:30',['Receive BBQ','Open buffet at 5:30','Ticket station operating','Welcome guests','Water/ice available','Kelly circulating','Campaign materials visible','Vertical photo/video begins','David prepares','Begin concert transition ~6:15','Clear acoustic equipment','Final buffet/room check']]]],
['production','Sound & Show','Tracy Morgan owns lights, sound and electrical, assisted by one campaign volunteer. ALL photo/video is vertical.',[
['Tracy + helper',['Confirm Tracy equipment list','Sound system','Speakers','Mixer','Microphones','Mic stands','Instrument inputs','Speaker stands','Cables','Power strips','Extension cords','Cable tape','Stage lights','Lighting stands','Spare batteries','Electrical outlets/circuits','Safe power distribution','Test microphones','Test inputs','Test speakers','Test lights','Full sound check','Any additional Tracy requirements']],
['David acoustic ~5:45–6:15',['Bar stool center floor','Acoustic guitar','Microphone','Mic stand','Acoustic amplification','Safe cable routing','Center-floor lighting','David water','Set/talking points','Test from stool position','Start ~5:45','Wrap ~6:15','Clear equipment before 6:30 doors']],
['7:00 concert',['Performers ready','Instruments ready','Stage microphones','Lights','Sound','Stage clear','Performer water','Opening/welcome','Introductions','Vertical photographer/video ready','Start promptly at 7:00','Monitor late arrivals','Monitor sound/lights']]]],
['timeline','Timeline','Event Captain owns transitions.',null,[
['8:00 AM','Venue access + 3-person setup','Setup + Tracy'],['10:00 AM','Room/power/production check','Setup + Tracy/helper'],['Early afternoon','Finish room, campaign, signs, lobby, merch, beverages, production','All leads'],['4:30 PM','Shift setup → event mode','Event Captain'],['5:00 PM','Event crew in position','Event Captain'],['5:30 PM','BBQ/social hour + buffet + tickets','Food + Ticket + Guest teams'],['Early event','Announce teardown need; committed teardown volunteers get free food','Event Captain'],['5:45 PM','David acoustic set','David + Production'],['6:15 PM','Acoustic wraps; transition','Event Captain'],['6:30 PM','Concert doors','Ticket + Door teams'],['6:45 PM','15-minute hard checkpoint','Event Captain + Tracy'],['7:00 PM','Concert','Show team'],['8:45–9:00 PM','Show ends; strike immediately','Teardown Captain'],['By 9:15 PM','Load-out well underway','Strike teams'],['By 9:45 PM','Final cleanup/walkthrough','Venue team'],['10:00 PM','Building cleared/secured','Event Captain']]],
['breakdown','Breakdown','Timed strike. No improvising after the show.',[
['Strike A — tables/chairs',['Clear tables','Remove tablecloths','Fold tablecloths','Clean tables','Fold round tables','Fold buffet tables','Fold 4-foot lobby table','Stack 64 chairs','Return furniture','Final furniture check']],
['Strike B — campaign/signs/merch',['Collect literature','Collect Kelly Craft memorabilia','Collect banners/displays','Collect QR signs','Pack campaign materials','Pack unused yard signs','Count remaining signs','Pack stakes','Collect roadside/entrance signs','Pack merch','Count remaining shirts','Check campaign/merch tables']],
['Strike C — food/drinks',['Clear BBQ','Handle leftovers appropriately','Food waste','Trash','Clean buffet tables','Remove buffet tablecloths','Collect bottled water','Consolidate drinks','Collect ice chests','Separate personal coolers','Collect glass beverage containers','Final food-area sweep']],
['Strike D — production',['Shut down sound','Shut down lights','Disconnect equipment','Coil cables','Pack microphones','Pack stands','Pack speakers','Pack mixer','Pack lighting','Account for all production','Load Tracy vehicle','Final stage check']],
['Strike E — venue',['Clear lobby','Clean main room','Check bathrooms','Remove trash','Check stage','Check all rooms/corners','Check parking/exterior','Lost-and-found','Final venue walkthrough','Meet venue requirements','Secure/lock building']],
['Load-out map',['Create vehicle/load-out map before Thursday','Production vehicle','Campaign/materials vehicle','Food/cooler vehicle','Merch vehicle','Separate personal belongings','Every item gets a destination','Final strike crew headcount','Event Captain confirms 10 PM clearance']]]],
['final','Final Sweep','Nothing is complete until inventory is accounted for and the venue is clear.',[
['Photography / video — VERTICAL ONLY',['Assign photographer/videographer','ALL footage vertical','Empty room','Setup','BBQ','Guest arrivals','Kelly greeting guests','David acoustic set','David with crowd','Full room','Kelly with supporters','Yard-sign pickup','Volunteers working','Concert','People enjoying/dancing','Closing/group shot','Short vertical social clips']],
['Event tote',['Pens','Sharpies','Scissors','Gaffer tape','Duct tape','Zip ties','Rubber bands','Safety pins','Paper towels','Trash bags','Hand sanitizer','Cleaning wipes','First-aid kit','Box cutter/multi-tool','Spare batteries','Extension cords','Power strips','Phone chargers','Battery packs']],
['Before leaving',['Count remaining signs','Count stakes','Collect campaign materials','Collect decorations','Collect tablecloths','Collect coolers','Collect glass beverage containers','Collect merchandise','Count shirts sold/remaining','Account for Regnet Populis giveaways','Ticket/cash/payment reconciliation','Secure contribution envelopes','Confirm vertical photos/video captured','Final venue walkthrough','Venue cleared/secured by 10 PM']]]]
];
const store=window.GGSPrepStore;const state=store?store.readCache():JSON.parse(localStorage.getItem('ggs-prep-2026-09-17-v2')||'{}');const root=document.getElementById('tabContent');
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function k(s,c,i){return `${s}:${c}:${i}`}
function render(){root.innerHTML=S.map((s,si)=>{const [id,title,intro,cards,timeline]=s;if(timeline)return `<section class="section ${si?'':'is-active'}" data-section="${id}"><div class="section-head"><p class="eyebrow">TIMELINE</p><h2>${title}</h2><p>${intro}</p></div><div class="card"><div class="timeline">${timeline.map((r,i)=>`<div class="time-row"><div class="time">${r[0]}</div><div><strong>${r[1]}</strong><div class="mini">${r[2]}</div><div class="task" data-key="${k(id,'timeline',i)}"><label class="check"><input class="task-check" type="checkbox"><span class="checkmark"></span><span class="task-text">Checkpoint complete</span></label><input class="owner" placeholder="Assigned to…"><input class="when" placeholder="Actual time…"></div></div></div>`).join('')}</div></div></section>`;return `<section class="section ${si?'':'is-active'}" data-section="${id}"><div class="section-head"><p class="eyebrow">EVENT COMMAND</p><h2>${title}</h2><p>${intro}</p></div><div class="grid">${cards.map((c,ci)=>`<article class="card"><h3>${c[0]}</h3><div class="checklist-actions"><button class="small-btn" data-complete="${id}|${ci}">Complete section</button><button class="small-btn" data-clear="${id}|${ci}">Clear section</button></div><div class="task-list">${c[1].map((t,ti)=>`<div class="task" data-key="${k(id,ci,ti)}"><label class="check"><input class="task-check" type="checkbox"><span class="checkmark"></span><span class="task-text">${esc(t)}</span></label><input class="owner" placeholder="Assigned to…"><input class="when" placeholder="When…"></div>`).join('')}</div></article>`).join('')}</div></section>`}).join('');bind();restore();progress()}
function saveRow(r){const c=r.querySelector('.task-check'),o=r.querySelector('.owner'),w=r.querySelector('.when');state[r.dataset.key]={done:c.checked,owner:o.value,when:w.value};if(store)store.saveOne(r.dataset.key,state[r.dataset.key]);else localStorage.setItem('ggs-prep-2026-09-17-v2',JSON.stringify(state));progress()}
function bind(){document.querySelectorAll('.task').forEach(r=>{['change','input'].forEach(e=>r.addEventListener(e,()=>saveRow(r)))});document.querySelectorAll('[data-complete],[data-clear]').forEach(b=>b.addEventListener('click',()=>{const [s,c]=b.dataset.complete?b.dataset.complete.split('|'):b.dataset.clear.split('|'),done=!!b.dataset.complete;document.querySelectorAll(`[data-section="${s}"] .card`)[+c].querySelectorAll('.task').forEach(r=>{const x=state[r.dataset.key]||{};x.done=done;state[r.dataset.key]=x;r.querySelector('.task-check').checked=done;if(store)store.saveOne(r.dataset.key,x)});if(!store)localStorage.setItem('ggs-prep-2026-09-17-v2',JSON.stringify(state));progress()}))}
function restore(){document.querySelectorAll('.task').forEach(r=>{const x=state[r.dataset.key];if(x){r.querySelector('.task-check').checked=!!x.done;r.querySelector('.owner').value=x.owner||'';r.querySelector('.when').value=x.when||''}})}
function progress(){const a=[...document.querySelectorAll('.task')],d=a.filter(x=>x.querySelector('.task-check').checked).length,p=a.length?Math.round(d/a.length*100):0;document.getElementById('progressPct').textContent=p+'%';document.getElementById('progressCount').textContent=`${d} / ${a.length}`;document.getElementById('progressBar').style.width=p+'%'}
document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>{x.classList.remove('is-active');x.setAttribute('aria-selected','false')});document.querySelectorAll('.section').forEach(x=>x.classList.remove('is-active'));t.classList.add('is-active');t.setAttribute('aria-selected','true');document.querySelector(`[data-section="${t.dataset.tab}"]`).classList.add('is-active');scrollTo(0,0)}));
document.getElementById('printBtn').addEventListener('click',()=>print());document.getElementById('resetBtn').addEventListener('click',()=>{if(confirm('Reset this shared event checklist?')){(store?store.reset():Promise.resolve()).then(()=>location.reload())}});render();if(store){window.addEventListener('ggs-prep-loaded',(e)=>{Object.keys(state).forEach((k)=>delete state[k]);Object.assign(state,e.detail||{});restore();progress()});store.load()}