const S=[
['overview','Overview','Lean night. 8 tables to dress. Merch is 30 minutes. Seven people work the clock and stay through 10.',[
['Event facts',['8:00 AM venue access — 3 dressers + Tracy/helper. Room can be done by 10:30.','8 guest tables to dress only. Venue already placed the 8 rounds + 64 chairs. Do not add tables.','Horseshoe + dance floor — venue already placed. Do not rebuild.','4 buffet tables at entry — venue already placed. Cloth only, 10 min.','4-foot lobby ticket table — venue already placed. Dress 10 min.','BBQ for 100 — Ben serves. We hold and refill, not a second kitchen.','5:30–6:30 PM BBQ/social — 1 food person + tickets + campaign + 2 floaters.','~5:45–6:15 PM David acoustic — Tracy + helper. 30 min set.','6:30 PM concert doors — tickets + one floater. 15 min rush.','7:00 PM concert — posts stay; floaters walk relief.','Show ends ~8:45–9:00 PM — same 7 strike, plus 3 muscle for Tracy sound/lights carry-out.','Building cleared by 10:00 PM — 75 min. Venue furniture stays.']],
['Tonight priorities',['Choose Event Captain — 5 min. Owns the clock, venue, and strike call.','Assign 3-person setup — they become Floater A, Floater B, and Campaign. Room dress ~90 min.','Lock the 7-person night roster. Same people stay through 10 PM.','Do not recruit a second full strike team. The 7 stay. Add 3 muscle only for Tracy sound/lights carry-out.','At 5:00 tell all 7: you stay until 10. Floaters cover breaks so nobody abandons a post.','Confirm Ben food/service list — 15 min phone call.','Confirm Tracy equipment list — 15 min.','Assign one campaign volunteer to assist Tracy — all day through Strike D.','Buy 8 gal unsweet tea, 6 gal lemonade, 120 bottles, 12 bags ice — 45 min store run.','Finalize ticket/payment process — 20 min before Thursday.','Name Photo Lead to roam for action and crowd. Kelly Support already shoots vertical on Kelly.','Load-out map: 4 vehicles. Venue furniture stays. Honest strike is 45–60 min if all 7 stay.','Someone must bring a bar stool for David’s acoustic set','Print all 8.5 x 11 signs at HQ — water, $25 door, volunteer, website — 20 min print.','Get Woody\'s Wi-Fi name and password. Enter them on the Wi-Fi page so every phone taps once to join']]]],
['ben','Ben / BBQ','Confirm exactly what Ben provides tonight. Use the owner field for the person handling each confirmation.',[
['Food for 100',['Pulled pork','Bread/buns','Potato salad','Baked beans','BBQ sauce/condiments','Serving pans/trays','Serving utensils','Tongs/ladles/spoons','Food covers','Warming/chafing equipment','Fuel if needed']],
['Disposable service',['Dinner plates — target 125','Forks — target 125','Knives — target 125','Spoons if needed — target 125','Napkins — target 125','Sandwich wrappers/baskets if needed','Cups if Ben provides them','Anything else Ben is providing']],
['Logistics',['Delivery/pickup','Exact food arrival time','Person receiving food','Ben setup requirements','Safe holding/serving plan','Equipment Ben needs from us','Final BEN PROVIDES list','Final WE PROVIDE list']]]],
['setup','Setup','Venue already placed the furniture. Three people dress 8 tables, then become night roles. Honest room time is about 90 minutes. Tracy and one helper own production — not this card.',[
['3-person setup crew',['Assign Setup Person 1 — becomes Floater A at 4:30 (relief loop all night)','Assign Setup Person 2 — becomes Floater B at 4:30 (relief + photo if needed)','Assign Setup Person 3 — becomes Campaign + merch after tables (30 min merch set)','Tables/chairs/dance floor — venue already in place from the floor plan. Do not rebuild.','Dress 8 guest tables only — 25 min for 3 people. Cloth + simple center.','Simple centers only — included in the 25 min. No second décor pass.','After tables: Setup 3 sets campaign/merch — 30 min. Pull-ups, push cards, buttons, candy, foldovers.','Place printed signs — 15 min. Setup 1+2 after the 8 tables.','Dress lobby ticket table — 10 min.','Confirm 8:00 AM arrival — three dressers. Done by ~10:30 if we stay on the clock.','Walk venue before unloading — 10 min.','Check exits/restrooms/guest flow — 5 min.','8 round tables — venue already placed. Confirm only. Then dress those 8.','64 chairs — venue already placed. Confirm only.','Horseshoe — venue already built. Do not rebuild.','Dance floor — venue already open in front of the stage. Do not rebuild.','Cloth 4 buffet tables — 10 min. Venue tables stay.','4-foot lobby table — venue already placed. Confirm only.','Set beverage station — 20 min. Tea, lemonade, sweeteners, cups. Ice waits until 4:30.','Set yard-sign pickup — 10 min. Park it next to the campaign table.','Campaign display is the 30 min merch job. Do not build a second booth.','Final room check — 10 min. Morning crew may leave after this.','Get Wi-Fi name and password from Woody\'s. Enter them on the Wi-Fi page. Every crew phone joins before radio','Ice and water coolers wait until 4:30 — Floater A + Food. Do not ice at 8 AM.','Morning crew may leave after the room is dressed. Be back by 4:30 in your night role.']]]],
['volunteers','Volunteers','Minimum night crew is 7. Use people twice. After setup, two floaters keep every post covered and give breaks. Same 7 stay through 10.',[
['Morning setup — 8:00 AM',['Recruit exactly 3 setup people — they are 3 of the 7 night people','Setup Person 1 — Floater A after 4:30','Setup Person 2 — Floater B after 4:30','Setup Person 3 — Campaign + merch after tables']],
['Event operations — 5:00 PM',['Event Captain — clock, venue, strike call. All night.','Primary ticket/check-in person — one body. Floater covers 10 min breaks.','Ticket backup is Floater A — not a second person parked at the table.','Food + $1 water + ice is ONE person. Ben is the vendor. You hold and refill.','No second food person. Floater B covers food breaks and the 6:30 refill.','Water + ice is the food person after 6:30. Same money bag.','Greeting is Kelly. Only Kelly Support mans her. Floater A is not her minder.','Campaign + merch — 1 person. 30 min set. Table 5:00–8:45. Floater relieves 10 min each hour.','Photo Lead roams for action and crowd shots. Journalistic. Not on Kelly all night.','Kelly works the room. Only Kelly Support mans her — runner plus vertical photos/video.','David support is Tracy helper + stool/water. No extra person.','Venue/trash/spills are Event Captain + Floater B.','Floater A + Floater B: after 4:30 they only relieve posts and run ice/trash. That is the job.','Tracy production helper — arrives 8:00 AM, stays through Strike D','Tell every crew member: join Woody\'s Wi-Fi from the Wi-Fi page before using radio']],
['Teardown recruitment',['Do not recruit a second strike crew. Confirm all 7 night people stay until 10.','Write the 7 night names plus 3 Tracy muscle on strike so V5 sends them at 8:45.','At 5:00 tell the crew: you stay. Guests may fold cloths if they want — not required.','Night crew eats. That is the deal — not a guest teardown pitch.','Strike pairs: A cloths (2), B campaign (2), C food (2), D Tracy + helper + 3 muscle on sound/lights, then everyone walks. Venue furniture stays.','At 8:30 Floater A tells each post: you stay. Building clear 10.','Event Captain is Strike Captain. No extra title.']],
['Arrival — parking and crowd',['Name parking volunteer — 5:00–7:00. Wave cars. Overflow if the lot fills.','Name directions volunteer — 5:00–7:00. Lot to door. BBQ inside, concert under the pavilion.','Name crowd/lobby volunteer — 5:00–7:00. Keep the line moving. Do not block doors. Point to tickets.']]]],
['tickets','Tickets & Money','Lock the admission and contribution process before doors.',[
['Lobby ticket station',['4-foot table — venue already placed. Confirm only.','Tablecloth — 2 min','Tickets — stack, 5 min','Guest list if applicable — one clipboard','Pens — 3 pens','Cash box/change — $100 in ones and fives','Electronic payment method if applicable','Print $25 door signs at HQ — 8.5 x 11','Event information — one half-sheet','Campaign QR codes — one stand, not a second table','Backup paper process — hash marks on one sheet','Primary ticket person — the only ticket body','Backup ticket person is Floater A for 10 min breaks + doors rush']],
['Ticket accounting',['Confirm ticket price(s)','Confirm cash acceptance','Confirm electronic payment method','Confirm refund/adjustment authority','Record ticket inventory before doors','Record tickets sold','Reconcile cash','Reconcile electronic payments','Secure event funds','Assign final reconciliation owner']],
['Contribution envelopes',['Prepare contribution envelopes','Prepare pens','Name field','Occupation field','Required contribution information fields','ANONYMOUS option for $25 contributions','$50 contribution envelope process','$100 contribution envelope process','Secure completed envelopes','Assign envelope custodian','End-of-night envelope count/reconciliation']]]],
['campaign','Campaign & Merch','One table. Honest setup is 30 minutes. Pack pull-ups, push cards, buttons, candy, and foldovers with the rest.',[
['Campaign materials',['Kelly Grappe literature — pack in one bin','Business/contact cards + push cards — same bin','Postcards — count, then pack','Door hangers if applicable — only if already printed','Buttons — pack a small box, not a second table','Campaign QR codes — two stands max','Volunteer signup information — one clipboard','Donation information — one QR, no extra booth','Campaign display — 30 min set with merch. Pull-up banners go here.','Campaign materials owner — Setup 3 / night campaign person','Print all 8.5 x 11 signs at HQ — water, $25 door, volunteer, website','Pull-up banners — pack and stand at the campaign table','Push cards — pack with literature','Buttons — pack with merch bin','Candy — small bowl on the campaign table','Foldover cards — pack with literature']],
['100 yard signs',['Confirm 100 signs — count once at HQ, 10 min','Confirm 100 stakes — same count','Count signs — do not recount on site unless a bundle breaks','Count stakes','Separate damaged signs — at HQ, not on site','Bundle signs — 10 min at HQ','Sign pickup station — one stack next to campaign. 5 min.','Sign request/sign-out — first name + phone on one sheet. 15 sec each.','Campaign person hands them out from the same table.','Record recipient name — one line on the sheet','Record recipient contact — same line','Record address/location as appropriate — only if they want a plant','Track distributed — tick marks','Count remaining — 5 min at strike']],
['Road / entrance signs',['Kelly Grappe signs for roadside — 6–8 max, not a highway crew','Place roadside signs where permitted — 20 min, Floater A at 4:30','Place entrance signs where permitted — 10 min','Check before doors — 5 min walk','Remove after event — 15 min during strike','Assign placement/removal owner — Floater A']],
['Merchandise',['Pick up Grassroots & Guitar Strings concert T-shirts from T-shirt shop in North Little Rock — before Thursday','Confirm pickup time','Count shirts — 10 min','Record sizes/quantities','Bring Regnet Populis shirts for giveaway','Set merch + campaign on ONE table — 30 min total. Not a store build.','Merch tablecloth — included in the 30 min','Concert T-shirt price/signage — one 8.5 x 11','Size display — stack by size, 5 min','Assign merch table owner — same as campaign owner','Payment method','Track shirts sold — hash marks, not a POS project','Track Regnet Populis shirts given away','Secure remaining merchandise — 10 min at strike']]]],
['food','Food & Drinks','BBQ/social hour is 5:30–6:30 PM for about 100 guests. Drink plan: 8 gallons unsweet tea + 6 gallons lemonade + 120 bottles of water (sell $1 and give away from that stock). Ice: 12 ten-pound bags.',[
['Beverages',['Unsweet tea — 8 gallons (~128 cups)','Lemonade — 6 gallons (~96 cups)','Bottled water — 120 bottles. Sell $1 and give away from this stock','Glass dispenser — unsweet tea','Glass dispenser — lemonade','Beverage dispensers/spigots','Cups if not supplied by Ben','Ice for tea/lemonade — 4 bags (10 lb)','Ice for 120 bottled waters — 6 bags (10 lb)','As many ice chests/coolers as possible','Label personal coolers','Water + ice captain owns coolers, $1 water, and giveaway water','Fill coolers before guests','Set beverage station with unsweet tea + Splenda/pink/blue packets','Replenish tea, lemonade, and water','Monitor/replenish ice','Collect/return coolers','Splenda, pink, and blue sweetener packets at the tea station','Spare ice — 2 bags (10 lb). Buy 12 bags / 120 lb total']],
['Buffet service',['Dress 4 buffet tables — 10 min. Cloth only.','Plan food flow — one line, 5 min talk with Ben.','Plates — set with Ben, 5 min','Utensils/napkins — set with Ben, 5 min','Pulled pork — Ben. We refill pans.','Bread/buns — Ben. We refill.','Potato salad — Ben. We refill.','Baked beans — Ben. We refill.','Sauces/condiments — set once, 5 min','Serving utensils — Ben or us, 5 min','Food covers — on until 5:30','Safe hot/cold holding — Ben owns heat.','Trash cans — 2 cans, 5 min','Hand sanitizer/paper towels — one station','Food person is BBQ 1 + water. No second food body.','Floater B is food relief — 10 min each hour, plus 6:30 refill.','Guests serve themselves. We keep pans full.','Monitor/replenish buffet — 5:30–6:30 only. Then food person moves to water.']],
['5:30–6:30',['Receive BBQ','Open buffet at 5:30','Ticket station operating','Welcome guests','$1 water + giveaway bottles open · 120 on ice','Kelly circulating','Campaign materials visible','Kelly Support starts vertical on Kelly. Photo Lead starts roaming the room','David prepares','Begin concert transition ~6:15','Clear acoustic equipment','Final buffet/room check']],
['$1 water station',['Assign Water + ice captain — same person sells water, gives water away, and runs ice','Print $1 water signs at HQ — 8.5 x 11, cash only','Post a sign at the cooler / beverage station','Post a second sign guests can see from the buffet line','Money bag for $1 cash donations','Ones for change','Pen and simple count sheet','Cash only — no cards and no QR at the water table','Do not send water money to any donate page','Confirm both printed signs say cash only','Keep extra ones in your pocket for change','Stock 120 bottled waters on ice — sell $1 or give away','Seller script: Water is a $1 donation, cash only — or take one complimentary.','Keep the money bag on the seller — not sitting open on the table','Reconcile the water bag with Event Captain at strike','Pack leftover water and the money bag']]]],
['production','Sound & Show','Tracy Morgan owns lights, sound, and electrical. One helper stays with him from 8:00 AM through Strike D. At encore, 3 more volunteers are muscle to break down the system and carry out lights and sound. Photo/video is a different person.',[
['Tracy + helper',['Tracy owns the one production system — do not build a second sound or light plot','Name the campaign volunteer helper — arrives 8:00 AM and stays through Strike D','Helper job: cables, tape, water, fetch. Do not leave at encore','Unload and place one system: speakers, mixer, mics, stands, lights','Map outlets and circuits — one safe power plan','Run and tape cables so the dance floor stays clear','Spare batteries staged at the mixer','One full sound and light check before guests','Write any extra Tracy requirement here','Name sound/lights muscle 1 — arrives 8:45. Carry speakers and stands. Tracy directs.','Name sound/lights muscle 2 — arrives 8:45. Carry lights and cases. Tracy directs.','Name sound/lights muscle 3 — arrives 8:45. Carry remaining production to Tracy\'s vehicle.']],
['David acoustic ~5:45–6:15',['Someone must bring a bar stool and set it center floor — venue does not provide one','David acoustic guitar + his amplification only','One vocal mic and stand at the stool','Center-floor light on David','David water at the stool','Test the acoustic position','Start ~5:45 PM','Wrap ~6:15 PM','Clear every piece of acoustic gear before 6:30 doors']],
['7:00 concert',['6:45 PM checkpoint with Event Captain — stage is ready','Run sound and lights for the 7:00 show','Stay on deck through the last song — then Strike D']]]],
['timeline','Timeline','Event Captain owns transitions.',null,[
['8:00 AM','Venue access. 3 dressers start the 90 min room. Tracy/helper on production.','Setup 1–3 + Tracy'],['10:00 AM','Room should be dressed. Production check. Morning crew may leave.','Setup + Tracy/helper'],['Early afternoon','No extra room work. Merch already set in 30 min. Ice waits until 4:30.','Leads only if something broke'],['4:30 PM','Night crew back. Ice water. Floaters start the relief loop.','Captain + floaters + food'],['5:00 PM','7 people on posts. 3 arrival people on parking, directions, and lobby crowd.','Event Captain'],['5:30 PM','BBQ/social. Tickets + food + campaign live. Floaters relieve every 30 min.','Food + Tickets + Campaign'],['Early event','Remind the 7: you stay until 10. Floaters give 10 min breaks.','Event Captain'],['5:45 PM','David acoustic — Tracy + helper. 30 min.','David + Production'],['6:15 PM','Acoustic clear. Floater B helps clear the floor.','Event Captain'],['6:30 PM','Concert doors. Tickets + Floater A. 15 min rush.','Tickets + Floater A'],['6:45 PM','15-minute hard checkpoint. Every post still has a body.','Event Captain + Tracy'],['7:00 PM','Concert. Floaters walk. One person always circulating.','Show + floaters'],['8:45–9:00 PM','Show ends. Same 7 strike. 3 muscle report to Tracy for sound/lights carry-out.','Event Captain'],['By 9:15 PM','Cloths packed. Campaign packed. Food packed. Production loading with 3 muscle.','The 7 + muscle'],['By 9:45 PM','Final walk. Venue furniture still where the venue put it.','Captain + Floater B'],['10:00 PM','Building cleared/secured','Event Captain']]],
['breakdown','Breakdown','Same 7 people plus 3 Tracy muscle on sound/lights. Venue furniture stays. Honest strike is 45–60 minutes if nobody leaves.',[
['Strike A — tables/chairs',['Clear 8 guest tables — 10 min, 2 people','Remove 8 tablecloths — do not touch venue furniture','Fold 8 tablecloths + 4 buffet cloths + lobby cloth','Wipe our spills only. Leave venue tables in place.','LEAVE the 8 round tables. Venue placed them.','LEAVE the buffet tables. Venue placed them.','LEAVE the 4-foot lobby table. Venue placed it.','LEAVE the 64 chairs. Do not restack the room.','Our stuff goes to vehicles. Furniture stays.','Final check: only our bins and cloths left to load']],
['Strike B — campaign/signs/merch',['Collect literature — 5 min','Collect Kelly Craft memorabilia — if any, 5 min','Collect pull-up banners + displays — 5 min','Collect QR signs — 2 min','Pack campaign bin: literature, push cards, foldovers, buttons, candy','Pack unused yard signs — 10 min','Count remaining signs — 5 min','Pack stakes','Collect roadside/entrance signs — Floater A, 15 min','Pack merch — 10 min','Count remaining shirts — 5 min','Check campaign/merch table is empty']]
['Strike C — food/drinks',['Clear BBQ','Handle leftovers appropriately','Food waste','Trash','Clean buffet tables','Remove buffet tablecloths','Collect bottled water','Consolidate drinks','Collect ice chests','Separate personal coolers','Collect glass beverage containers','Final food-area sweep']],
['Strike D — production',['Shut down sound','Shut down lights','Disconnect equipment','Coil cables','Pack microphones','Pack stands','Pack speakers','Pack mixer','Pack lighting','Account for all production','Load Tracy vehicle — helper + 3 muscle carry. Tracy directs. No empty hands.','Final stage check','Sound/lights muscle 1 carries speakers and stands out','Sound/lights muscle 2 carries lights and cases out','Sound/lights muscle 3 carries remaining production to the vehicle']],
['Strike E — venue',['Clear lobby','Clean main room','Check bathrooms','Remove trash','Check stage','Check all rooms/corners','Check parking/exterior','Lost-and-found','Final venue walkthrough','Meet venue requirements','Secure/lock building']],
['Load-out map',['Create vehicle/load-out map before Thursday — 10 min','Production vehicle — Tracy','Campaign/materials vehicle — banners, bins, signs','Food/cooler vehicle — Ben leftover + our drinks','Merch rides with campaign — not a fifth van','Separate personal belongings — one tote','Every item gets a destination','Final headcount is the same 7 plus 3 Tracy muscle','Event Captain confirms 10 PM clearance']]]],
['final','Final Sweep','Nothing is complete until inventory is accounted for and the venue is clear.',[
['Photography / video — two jobs',['Kelly Support shoots vertical on Kelly. Only support staff mans her. Photo Lead is a different person.','Photo Lead: roam. Action shots of Kelly and the crowd. Journalistic photography. Not parked on her all night.','Kelly Support: ALL her footage is vertical','Empty room','Setup','BBQ','Guest arrivals','Kelly greeting guests — Support, vertical, from her side','David acoustic set','David with crowd','Full room — Photo Lead roams this','Kelly with supporters — Support stays on her','Yard-sign pickup','Volunteers working — Photo Lead','Concert — Photo Lead action and crowd','People enjoying/dancing — Photo Lead','Closing/group shot','Short vertical social clips — Kelly Support','If Photo Lead is empty, Floater B grabs roam frames between loops — still not Kelly Support']],
['Event tote',['Pens','Sharpies','Scissors','Gaffer tape','Duct tape','Zip ties','Rubber bands','Safety pins','Paper towels','Trash bags','Hand sanitizer','Cleaning wipes','First-aid kit','Box cutter/multi-tool','Spare batteries','Extension cords','Power strips','Phone chargers','Battery packs']],
['Before leaving',['Count remaining signs','Count stakes','Collect campaign materials','Collect decorations','Collect tablecloths','Collect coolers','Collect glass beverage containers','Collect merchandise','Count shirts sold/remaining','Account for Regnet Populis giveaways','Ticket/cash/payment reconciliation','Secure contribution envelopes','Confirm vertical photos/video captured','Final venue walkthrough','Venue cleared/secured by 10 PM']]]]
];
window.GGS_PREP_SECTIONS=S;
if(document.getElementById('prepApp')||!document.getElementById('tabContent')){/* v3 / personal page owns render */}
else{
const store=window.GGSPrepStore;const state=store?store.readCache():JSON.parse(localStorage.getItem('ggs-prep-2026-09-17-v2')||'{}');const root=document.getElementById('tabContent');
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function k(s,c,i){return `${s}:${c}:${i}`}
function render(){root.innerHTML=S.map((s,si)=>{const [id,title,intro,cards,timeline]=s;if(timeline)return `<section class="section ${si?'':'is-active'}" data-section="${id}"><div class="section-head"><p class="eyebrow">TIMELINE</p><h2>${title}</h2><p>${intro}</p></div><div class="card"><div class="timeline">${timeline.map((r,i)=>`<div class="time-row"><div class="time">${r[0]}</div><div><strong>${r[1]}</strong><div class="mini">${r[2]}</div><div class="task" data-key="${k(id,'timeline',i)}"><label class="check"><input class="task-check" type="checkbox"><span class="checkmark"></span><span class="task-text">Checkpoint complete</span></label><input class="owner" placeholder="Assigned to…"><input class="when" placeholder="Actual time…"></div></div></div>`).join('')}</div></div></section>`;return `<section class="section ${si?'':'is-active'}" data-section="${id}"><div class="section-head"><p class="eyebrow">EVENT COMMAND</p><h2>${title}</h2><p>${intro}</p></div><div class="grid">${cards.map((c,ci)=>`<article class="card"><h3>${c[0]}</h3><div class="checklist-actions"><button class="small-btn" data-complete="${id}|${ci}">Complete section</button><button class="small-btn" data-clear="${id}|${ci}">Clear section</button></div><div class="task-list">${c[1].map((t,ti)=>`<div class="task" data-key="${k(id,ci,ti)}"><label class="check"><input class="task-check" type="checkbox"><span class="checkmark"></span><span class="task-text">${esc(t)}</span></label><input class="owner" placeholder="Assigned to…"><input class="when" placeholder="When…"></div>`).join('')}</div></article>`).join('')}</div></section>`}).join('');bind();restore();progress()}
function saveRow(r){const c=r.querySelector('.task-check'),o=r.querySelector('.owner'),w=r.querySelector('.when');state[r.dataset.key]={done:c.checked,owner:o.value,when:w.value};if(store)store.saveOne(r.dataset.key,state[r.dataset.key]);else localStorage.setItem('ggs-prep-2026-09-17-v2',JSON.stringify(state));progress()}
function bind(){document.querySelectorAll('.task').forEach(r=>{['change','input'].forEach(e=>r.addEventListener(e,()=>saveRow(r)))});document.querySelectorAll('[data-complete],[data-clear]').forEach(b=>b.addEventListener('click',()=>{const [s,c]=b.dataset.complete?b.dataset.complete.split('|'):b.dataset.clear.split('|'),done=!!b.dataset.complete;document.querySelectorAll(`[data-section="${s}"] .card`)[+c].querySelectorAll('.task').forEach(r=>{const x=state[r.dataset.key]||{};x.done=done;state[r.dataset.key]=x;r.querySelector('.task-check').checked=done;if(store)store.saveOne(r.dataset.key,x)});if(!store)localStorage.setItem('ggs-prep-2026-09-17-v2',JSON.stringify(state));progress()}))}
function restore(){const active=document.activeElement;document.querySelectorAll('.task').forEach(r=>{if(active&&r.contains(active))return;const x=state[r.dataset.key];if(x){r.querySelector('.task-check').checked=!!x.done;r.querySelector('.owner').value=x.owner||'';r.querySelector('.when').value=x.when||''}})}
function progress(){const a=[...document.querySelectorAll('.task')],d=a.filter(x=>x.querySelector('.task-check').checked).length,p=a.length?Math.round(d/a.length*100):0;document.getElementById('progressPct').textContent=p+'%';document.getElementById('progressCount').textContent=`${d} / ${a.length}`;document.getElementById('progressBar').style.width=p+'%'}
document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>{x.classList.remove('is-active');x.setAttribute('aria-selected','false')});document.querySelectorAll('.section').forEach(x=>x.classList.remove('is-active'));t.classList.add('is-active');t.setAttribute('aria-selected','true');document.querySelector(`[data-section="${t.dataset.tab}"]`).classList.add('is-active');scrollTo(0,0)}));
document.getElementById('printBtn').addEventListener('click',()=>print());document.getElementById('resetBtn').addEventListener('click',()=>{if(confirm('Reset this shared event checklist?')){(store?store.reset():Promise.resolve()).then(()=>location.reload())}});render();if(store){window.addEventListener('ggs-prep-loaded',(e)=>{Object.keys(state).forEach((k)=>delete state[k]);Object.assign(state,e.detail||{});restore();progress()});window.addEventListener('ggs-prep-status',(e)=>{const el=document.getElementById('syncStatus');if(!el)return;el.textContent=e.detail==='saving'?'Saving to every device…':e.detail==='offline'?'Shared board unreachable — this phone only until it reconnects.':'Shared across every device. No refresh needed.';el.dataset.state=e.detail||'ok'});store.startSync()}
}