CREATE TABLE IF NOT EXISTS prep_assignments (
  task_key TEXT PRIMARY KEY,
  owner TEXT NOT NULL DEFAULT '',
  due_when TEXT NOT NULL DEFAULT '',
  done BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
